#!/usr/bin/env node
/** Embed public/static/app.js (+ marketing landing) into a TS module the Worker can import. */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = path.join(root, 'public/static/app.js');
const marketingPath = path.join(root, 'public/static/marketing/index.html');
const comparePath = path.join(root, 'public/static/marketing/compare.html');
const demoPath = path.join(root, 'public/static/marketing/demo.html');
const demoJsPath = path.join(root, 'public/static/demo-experience.js');
const platformGuideJsPath = path.join(root, 'public/static/platform-guide.js');
const outDir = path.join(root, 'src/generated');
const outPath = path.join(outDir, 'spa-source.ts');

mkdirSync(outDir, { recursive: true });
const source = readFileSync(srcPath, 'utf8');
const swSource = readFileSync(path.join(root, 'public/sw.js'), 'utf8');
const manifestSource = readFileSync(path.join(root, 'public/manifest.webmanifest'), 'utf8');
const marketingSource = existsSync(marketingPath)
  ? readFileSync(marketingPath, 'utf8')
  : '<!DOCTYPE html><html><body><p>Smart FCRA marketing page missing.</p></body></html>';
const compareSource = existsSync(comparePath)
  ? readFileSync(comparePath, 'utf8')
  : marketingSource;
const demoSource = existsSync(demoPath)
  ? readFileSync(demoPath, 'utf8')
  : marketingSource;
const demoJsSource = existsSync(demoJsPath)
  ? readFileSync(demoJsPath, 'utf8')
  : 'window.SmartFcraDemo={mount(){},boot(){}};';
const platformGuideJsSource = existsSync(platformGuideJsPath)
  ? readFileSync(platformGuideJsPath, 'utf8')
  : 'window.SmartFcraGuide={mount(){},boot(){},startTour(){},resumeTour(){},openAsk(){},getProgress(){return{}},ask(){}};';
writeFileSync(
  outPath,
  `/* Auto-generated by scripts/embed-spa.mjs — do not edit */\n` +
  `export const spaAppSource: string = ${JSON.stringify(source)};\n` +
  `export const pwaSwSource: string = ${JSON.stringify(swSource)};\n` +
  `export const pwaManifestSource: string = ${JSON.stringify(manifestSource)};\n` +
  `export const marketingLandingHtml: string = ${JSON.stringify(marketingSource)};\n` +
  `export const marketingCompareHtml: string = ${JSON.stringify(compareSource)};\n` +
  `export const marketingDemoHtml: string = ${JSON.stringify(demoSource)};\n` +
  `export const demoExperienceSource: string = ${JSON.stringify(demoJsSource)};\n` +
  `export const platformGuideSource: string = ${JSON.stringify(platformGuideJsSource)};\n`,
);
console.log(`[embed-spa] wrote ${outPath} (app ${source.length}, marketing ${marketingSource.length}, demo ${demoSource.length}, demoJs ${demoJsSource.length}, guideJs ${platformGuideJsSource.length})`);
