#!/usr/bin/env node
/** Embed public/static/app.js into a TS module the Worker can import (tsx + vite safe). */
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = path.join(root, 'public/static/app.js');
const outDir = path.join(root, 'src/generated');
const outPath = path.join(outDir, 'spa-source.ts');

mkdirSync(outDir, { recursive: true });
const source = readFileSync(srcPath, 'utf8');
writeFileSync(
  outPath,
  `/* Auto-generated by scripts/embed-spa.mjs — do not edit */\nexport const spaAppSource: string = ${JSON.stringify(source)};\n`,
);
console.log(`[embed-spa] wrote ${outPath} (${source.length} chars)`);
