#!/usr/bin/env node
/** Embed public/static/app.js into a TS module the Worker can import (tsx + vite safe). */
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = path.join(root, 'public/static/app.js');
const outDir = path.join(root, 'src/generated');
const outPath = path.join(outDir, 'spa-source.ts');

mkdirSync(outDir, { recursive: true });
const source = readFileSync(srcPath, 'utf8');
const swSource = readFileSync(path.join(root, 'public/sw.js'), 'utf8');
const manifestSource = readFileSync(path.join(root, 'public/manifest.webmanifest'), 'utf8');
writeFileSync(
  outPath,
  `/* Auto-generated by scripts/embed-spa.mjs — do not edit */\n` +
  `export const spaAppSource: string = ${JSON.stringify(source)};\n` +
  `export const pwaSwSource: string = ${JSON.stringify(swSource)};\n` +
  `export const pwaManifestSource: string = ${JSON.stringify(manifestSource)};\n`,
);
console.log(`[embed-spa] wrote ${outPath} (app ${source.length}, sw ${swSource.length}, manifest ${manifestSource.length})`);
